# Generated by Django 5.0.6 on 2026-04-09 14:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('entry_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('take_profit', models.DecimalField(decimal_places=6, max_digits=20)),
                ('stop_loss', models.DecimalField(decimal_places=6, max_digits=20)),
                ('tp_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sl_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED_TP', 'Closed (Take Profit)'), ('CLOSED_SL', 'Closed (Stop Loss)'), ('CLOSED_MAN', 'Closed (Manual)')], default='OPEN', max_length=20)),
                ('pnl', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
