# Generated by Django 5.2.13 on 2026-05-07 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('min_confidence_crypto', models.FloatField(default=65.0)),
                ('min_confidence_forex', models.FloatField(default=62.0)),
                ('min_confidence_gold', models.FloatField(default=63.0)),
                ('max_open_trades', models.IntegerField(default=3)),
                ('cooldown_minutes', models.IntegerField(default=30)),
                ('daily_loss_limit', models.IntegerField(default=3)),
                ('selected_symbols', models.JSONField(default=list, help_text='List of symbols bot is allowed to trade')),
                ('total_bot_trades', models.IntegerField(default=0)),
                ('total_bot_wins', models.IntegerField(default=0)),
                ('total_bot_losses', models.IntegerField(default=0)),
                ('daily_loss_count', models.IntegerField(default=0)),
                ('last_reset_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SCAN', 'Scanned Symbol'), ('OPEN', 'Opened Trade'), ('SKIP', 'Skipped Signal'), ('CLOSE', 'Trade Closed'), ('PAUSE', 'Bot Paused'), ('ERROR', 'Error Occurred')], max_length=10)),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('direction', models.CharField(blank=True, max_length=10)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
