# Generated by Django 5.2.13 on 2026-05-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_alter_chatmessage_metadata_conversation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='pnl',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
