# Generated by Django 5.2.13 on 2026-05-26 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_alter_trade_pnl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='bot_fixed_amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=15),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='bot_fixed_quantity',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=15),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=15),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='starting_balance',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=15),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='trade',
            name='direction',
            field=models.CharField(choices=[('BUY', 'Buy (Long)'), ('SELL', 'Sell (Short)')], default='BUY', max_length=4),
        ),
        migrations.AddField(
            model_name='trade',
            name='quantity',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=15),
        ),
        migrations.AlterField(
            model_name='trade',
            name='entry_price',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stop_loss',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='trade',
            name='take_profit',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
