# Generated by Django 5.2.13 on 2026-05-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_agentconfig_bot_fixed_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='current_balance',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='starting_balance',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='userbalance',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=15),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='starting_balance',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=15),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='entry_price',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stop_loss',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='take_profit',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
    ]
